server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_qt
    username: qt_analytics
    password: qt_analytics
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
init-setting:
  usersRoles:
    - role: ROLE_ADMIN
      nameRole: Администратор
  usersInitList:
    - name: Владимир
      surName: Вячеславович
      lastNName: Вторушин
      email: wtorushin@yandex.ru
      password: 1111
      role: ROLE_ADMIN
    - name: Полина
      surName: Анатольевна
      lastNName: Закамская
      email: p.zakam@quartztop.ru
      password: 1111
      role: ROLE_ADMIN