server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
app:
  integration:
    base-url: https://api.moysklad.ru/api/remap/1.2/entity/